### ISSUE TITLE
[Request for help] Examples of how to access secrets in code

### ISSUE THREAD

**Issue by markmcgookin** [Azure/kubernetes-keyvault-flexvol#108]
Hi, 

I've managed to get a K8s cluster setup, setup a CI pipeline for my code to be deployed to a container and pushed to my cluster, I've configured flexvolume, tested it works... but my code is failing. I assume this is because I am assuming that the default IConfiguration integration of keyvault would just work with this. 

Is there something different I need to do in code (should I literally loop through the mounted volume files and create a secret store in memory?) to access these secrets? Are there any examples out there?

Regards, 

Mark

**Comment by kanistha** [comment]
I am trying to integrate the Azure Key Vault using Kuberenetes flexvolume by using a service principal. I have done the steps for key vault configuration and able to load the secrets from flex volume following the steps in https://github.com/Azure/kubernetes-keyvault-flexvol in kubectl. Now I want to read the secrets from Flex-volume into my code. My app is in nodeJS. 

```
> kubectl exec -it nginx-flex-kv cat /secret1/testSecret
Defaulting container name to nginx-flex-kv.
Use 'kubectl describe pod/nginx-flex-kv -n default' to see all of the containers in this pod.
shhhhh%
```

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: secret-test
      mountPath: /secret1
      readOnly: true
  volumes:
  - name: secret-test
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds 
      options:
        usepodidentity: "false"
        resourcegroup: "testApp-test"
        keyvaultname: "testApp-kv"
        keyvaultobjectname: "testSecret"
        keyvaultobjecttype: secret # OPTIONS: secret, key, cert
        keyvaultobjectversion: "<ID>"
        subscriptionid: "<ID>"
        tenantid: "<ID>"
```

How I can load the secret value into my environment variable or a constant?
