### ISSUE TITLE
MountVolume.SetUp failed for volume "xxx":  invalid character '\r' in string literal

### ISSUE THREAD

**Issue by sukruthakittur** [Azure/kubernetes-keyvault-flexvol#120]
**Describe the bug**
MountVolume.SetUp failed for volume "xxx":  invalid character '\r' in string literal

**Steps To Reproduce**
1. Add SPN secret to kube -
kubectl create secret generic kvcreds --from-literal clientid=CLIENTID --from-literal clientsecret=CLIENTSECRET --type=azure/kv

2. Deploy yml
kubectl create -f deployment/nginx-flex-kv.yaml

Here is my deployment yaml. I also modified the nginx-flex-kv yml file to match the below settings.

```
spec:
      containers:
      - name: nginx-flexkv
        image: nginx
        volumeMounts:
        - name: kv
          mountPath: /kvmnt
          readOnly: true
      volumes:
      - name: kv
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: eecreds
          options: 
            usepodidentity: "false"
            keyvaultname: "my-vault"
            keyvaultobjectnames: test          
            keyvaultobjecttypes: key            
            resourcegroup: "my-group"       
            subscriptionid: "subscriptionid"        
            tenantid: "tenantid"    
```

**Expected behavior**
Should mount the volume

**Key Vault FlexVolume version**
Latest

**Access mode: service principal or pod identity**
Service Principal

**Kubernetes version**
Client Version: v1.13.2
Server Version: v1.13.7

**Additional context**
I am not sure if there is something wrong with my yml file. I validated the deployment yml and nginx-flex-kv.yml and they seem to be valid yaml files.
