### ISSUE TITLE
Create PEM files directly in volumes

### ISSUE THREAD

**Issue by aelij** [Azure/kubernetes-keyvault-flexvol#151]
**Describe the request**
Currently KVFV allows fetching certificates in the PFX format, which is not usable by many Linux components. It's possible to use `initContainers` and call `openssl` to [convert them](https://github.com/Azure/kubernetes-keyvault-flexvol/blob/master/docs/traefik-tls-certificate.md), but it would be much simpler if the extension would convert to PEM files by specifying an option.

**Describe the solution you'd like**
Specify an option, e.g. `secretformat`
```yaml
flexVolume:
    driver: "azure/kv"
    options:
        keyvaultname: "myvault"
        keyvaultobjectname: "cert1"
        keyvaultobjecttype: "secret"
        secretformat: "pem"
```

**Describe alternatives you've considered**
Convert in each pod using `initContainers`.
