### ISSUE TITLE
Support 1.17.0

### ISSUE THREAD

**Issue by snodnipper** [Azure/kubernetes-keyvault-flexvol#168]
**Describe the bug**
When using 1.17.0 AKS I encountered the following error.  Returning to 1.15.5 worked fine.

```shell
unable to recognize "https://raw.githubusercontent.com/Azure/kubernetes-keyvault-flexvol/master/deployment/kv-flexvol-installer.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```

**Key Vault FlexVolume version**
keyvault-flexvolume:v0.0.15

**Kubernetes version**
1.17.0

**Comment by aramase** [comment]
@snodnipper The apiVersion `extensions/v1beta1` has been deprecated as of 1.16+. We will update the api version in the manifest to `apps/v1`. Thank you for opening the issue.

**Comment by ohthehugemanatee** [comment]
also, the spec for a DaemonSet now requires a spec.selector value which matches the metadata for the pod itself. Used to tell which pods were started by this Daemonset.  So it should look like
```
...
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: keyvault-flexvolume
  name: keyvault-flexvolume
  namespace: kv
spec:
  selector:
    matchLabels:
      app: keyvault-flexvolume
  updateStrategy:
    type: RollingUpdate
  template:
...
```

I would open a PR, but I'm not sure how you deal with backwards compatibility for this kind of breaking change.
