### ISSUE TITLE
Syntax for keyvaultobjects should use yaml dictionaries instead of strings

### ISSUE THREAD

**Issue by jmspring** [Azure/kubernetes-keyvault-flexvol#175]
Currently, if one wishes to expose one or more keyvault objects via Flexvolume, you must manually concat the information for each object across multiple string values:

        keyvaultobjectnames
        keyvaultobjectaliases
        keyvaultobjecttypes
        keyvaultobjectversions

With values for each object separated by a delimiter.   `keyvaultobjectaliases` and `keyvaultobjectversions` are optional, but if you need such for any one of the object, you would need to add such for *every* object.  This makes the management of even a small (less than 10) number of objects unwieldy.  

It would make more sense to represent these values as a list of dictionaries as follows:

```
keyvaultobjects:
  - name: foo
     type: secret
  - name: bar
     type: secret
     version: 1
  - name: cat
     type: secret
     version: 12
     alias: settings.json
```

While it is more "verbose" it is more practical and flexible.
