### ISSUE TITLE
Support env variables

### ISSUE THREAD

**Issue by timwebster9** [Azure/kubernetes-keyvault-flexvol#28]
It looks like this doesn't use actual Kubernetes secrets object correct?  And the only way for an application to access a secret inside a container is to read from the filesystem (that is, the volume mount)?

Just looking for clarity - thanks.

**Comment by ritazh** [comment]
That is correct.  Instead of maintaining your application secrets as k8s secrets within the cluster, this solution provides your pods/containers an alternate secure way to retrieve application secrets stored outside of the cluster by using this k8s flex volume to communicate with Azure Key Vault. 

Hope this help.s Let me know if you have other questions or concerns.

**Comment by timwebster9** [comment]
Ok thanks.  So one concern is that I've seen organisations put a lot of effort into converting their applications into microservices that are configured with environment variables as per the 12-factor app, so it looks like that won't work with this.  

I'm just curious regarding the decisions behind doing it this way (with volumes).  I've seen other integrations do it this way as well, is this the new best-practice for managing secrets in kubernetes?

**Comment by ritazh** [comment]
> microservices that are configured with environment variables 

This is a good feedback. Will think about how to enable this. 

> decisions behind doing it this way (with volumes)

Doing it with volume was intended to make it easier for developers to adopt this by adding the flexvolume reference as part of their existing application deployment yaml as oppose to say adding another sidecar container just for this purpose.

> is this the new best-practice for managing secrets in kubernetes

Today many organizations have concerns around storing and maintaining application secrets as k8s secrets in the cluster. Even with RBAC enabled, there is still chance where the wrong pod might get access to secrets for another pod. Another concern is around how secrets are stored and updated as part of CI/CD process which means the secrets are actually part of the codebase. This solution was created to address these concerns to allow organizations to: 
- store and maintain their application secrets outside of the cluster in a secure key vault store
- access application secrets easily by adding this flexvolume to their application deployment yaml

Hope this helps.

**Comment by timwebster9** [comment]
Thanks - that makes sense.  It's good to know where things are going.

I'm glad to hear you will think about support for environment variable configuration.  Even if it's not best practice at the moment, supporting it will make migrating the application much easier (both to containers and to use volumes).

**Comment by nphmuller** [comment]
I understand that it’s really bad practice to keep secrets in env vars, but we also have some legacy applications that only work that way and are really hard to change.

It would be really great if this scenario could be supported (but feel free to discourage it as hard as possible in the docs :) )

**Comment by Ravibabu-Nannuri** [comment]
Is this feature ready to use ?

**Comment by ritazh** [comment]
We definitely hear you that migrating solutions that use env vars is going to be a challenge and an education. But collectively we felt that it’s not something we should support. We could perhaps start by updating common applications that use env vars today and show users how to do that more efficiently.

**Comment by Ravibabu-Nannuri** [comment]
Is there any example deployment which we can refer to use the AKV secrets with POD?

**Comment by ritazh** [comment]
@Ravibabu-Nannuri You can take a look at this: https://github.com/Azure/kubernetes-keyvault-flexvol#use-the-keyvault-flexvolume

**Comment by martin2176** [comment]
@ritazh 
I am afraid I disagree with the notion that ENV variables is a bad idea. 
Its not the ENV variables which is bad, its storing secrets inside K8S and using those stored secrets as ENV variables which makes in insecure.
A lot if not all images on Container registries use ENV variables to modify the behavior of application. Very few (if any) provide an option to read variables from a file (a mounted file inside the container). 
The problem is not just with legacy applications. Every docker image out there use ENV variables.

I understand Flex Volume is a mount point and there is nothing you guys can do to make it available as an ENV variable. Lack of ENV variable limits the usability of KV Flex Volume because two different ways of managing secrets beats the whole purpose.

**Comment by ritazh** [comment]
@martin2176 one workaround is to set the environment variable before the main process starts in your container. For example:
```
...
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    command: ["/bin/sh", "-c", "export SECRET=$(cat /kvmnt/mysecret); echo $SECRET; nginx -g 'daemon off;'"]
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
...
```

**Comment by bartb01** [comment]
@ritazh Hi, your example is for the nginx container specifically. However, what if an image for microservices is provided and you do not know the start command? My point is, the container would be running fine normally, but when you add a command to the deployment file, only this will be executed and then the status becomes 'completed'. I tried adding a 'sleep infintely' to keep the container running but this does not run the startscript in he image. Futhermore, I think the added command (to export an env var) is executed in a subshell? therefore, if one would connect to the container afterwards, the 'main'shell would not have this environment variable?

**Comment by deepak0917** [comment]
@bartb01 -  you are right, the command is executed in a subshell. To have the parent shell have this env variable, you should do this. 

**command: [“/bin/sh”, “-c”, “echo ‘export TESTSECRET=$(cat /kvmnt/mysecret)’ >> ~/.bashrc; tail -f /dev/null;“]**

**Comment by bartb01** [comment]
@deepak0917 thanks for your reply! I cannot look inside the image so its not possible for me to get the startcommand. I have tried executing your command (without tail-ing /dev/null) in a postStart lifecycle:

```
- image: img:tag
        name: name
        lifecycle:
          postStart:
            exec:
              command: [“/bin/sh”, “-c”, “echo ‘export TESTSECRET=$(cat /kvmnt/mysecret)’ >> ~/.bashrc“]
```

 However this unfortunately only creates the environment variable when logging into a shell (e.g. kubectl exec -it <pod> bash)
I tried it with etc/environment and etc/profile.d/setenv.sh aswell, for system wide env vars, but it does not create the environment variable without connecting to the container..

**Comment by allantargino** [comment]
Hi @ritazh,

It would be super nice if we could use a structure like this:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    env:
      - name: TEST_SECRET
        valueFrom:
          flexVolumeRef:
            name: test_flex
            key: secret-name
            path: /kvmnt
            [...]
```

I was wondering if we could try submit code on the upstream to implement that.
I don't know if this would be the best way, but how about:
1. We create a new `FlexVolumeRefSelector`, like [this one](https://github.com/kubernetes/kubernetes/blob/20b76a2b4a3e3551241a21afe464ca1612624ca1/pkg/apis/core/types.go#L1756)
2. Then we add a new case for `case envVar.ValueFrom.ConfigMapKeyRef != nil:`  [in this loop](https://github.com/kubernetes/kubernetes/blob/62f5fd4c6c96ed33fb67aca8740ae660548f21df/pkg/kubelet/kubelet_pods.go#L663), like [this one](https://github.com/kubernetes/kubernetes/blob/62f5fd4c6c96ed33fb67aca8740ae660548f21df/pkg/kubelet/kubelet_pods.go#L685)
3. We implement the logic of attaching/mounting the FlexVolume in the master, retrieve the secrets and parse it into the environment variables.

How problematic would it be mouting the FlexVolume in the master? Is it a feasible  approach?

**Comment by markmcgookin** [comment]
> @martin2176 one workaround is to set the environment variable before the main process starts in your container. For example:
> 
> ```
> ...
> spec:
>   containers:
>   - name: nginx-flex-kv
>     image: nginx
>     command: ["/bin/sh", "-c", "export SECRET=$(cat /kvmnt/mysecret); echo $SECRET; nginx -g 'daemon off;'"]
>     volumeMounts:
>     - name: test
>       mountPath: /kvmnt
>       readOnly: true
> ...
> ```

How would one update this to export all values from /kvmnt/ to environment variables, assuming there were multiple secrets stored? (Apologies, bash amateur here)

**Comment by martyncrow** [comment]
I agree with @martin2176 
I feel that there are alot of containers out there that still use env vars as a way to change the behaviour of an application. I appreciate that env vars is not the best approach but using FlexVol to access the KeyVault isn't very helpful in 90% of cases. Maybe providing an interim approach that injects the env variables directly into the container is a compromise. something similar to this might help [here](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes)

**Comment by KZeronimo** [comment]
Agree with @martin2176  - the [azure-keyvault-to-kubernetes](https://github.com/SparebankenVest/azure-key-vault-to-kubernetes) project has some good ideas around injecting secrets thru env variables in a secure manner - [intro blog](https://mrdevops.io/introducing-azure-key-vault-to-kubernetes-931f82364354) is worth a read.

@ritazh any chance these projects can cross-pollinate?

**Comment by MatejMalicek** [comment]
I can confirm that I have adopted @ritazh 's approach successfully for a Redis configuration that sets a password for Redis. The password is mounted from KeyVault and then read into a variable that is passed into the redis-start command.

This worked with AAD-Pod-Identity enabled (user-assigned managed identity).

Working sample YAML below (just replace necessary values with your own):
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: db
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        aadpodidbinding: "binding-name"
    spec:
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
        - name: kv-flex
          flexVolume:
            driver: "azure/kv"
            options:
              usepodidentity: "true"
              keyvaultname: "keyvault-name"  
              keyvaultobjectnames: "redispassword"
              keyvaultobjecttypes: secret 
              keyvaultobjectversions: ""
              resourcegroup: "KeyVaultRG"
              subscriptionid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
              tenantid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      initContainers:
        - name: disable-thp
          image: redis:4.0-alpine 
          volumeMounts:
            - name: host-sys
              mountPath: /host-sys
          command: ["sh", "-c", "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"]
      containers:
      - name: redis
        image: redis:4.0-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: kv-flex
          mountPath: /kvmnt
          readOnly: true
        command: ["/bin/sh"]
        args: ["-c", "REDISPASS=`cat /kvmnt/redispassword`; redis-server --requirepass $REDISPASS --maxmemory 700mb --maxmemory-policy allkeys-lru"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: db
  labels:
    app: redis 
spec:
  ports:
  - port: 6379 
    name: redis
  selector:
    app: redis 
```

Really, if a pod is compromised, then storing things in environment variables is no safer than mounting the secrets to disk. It would be extremely difficult to create a configuration where the process that is running an application within the container would be able to use a secret without having read access to it. My main issue with storing secrets in files & K8s secrets (rather than env vars) is that files can inadvertently be committed to source control, secrets can make their way into pipelines, secrets can be read by the K8s controller and perhaps other pods. If a pod is compromised, then it should be assumed that everything that the pod can read can be read by an attacker.

The approach of using FlexVolume will not (and cannot) mitigate against the threat of secret exposure if a pod is compromised - the point of compromise will generally be the exposed process and that process needs read access to secrets. The purpose of mitigations like FlexVolume and the storing of secrets in environment variables is not to mitigate against exposure on pod compromise, but rather to mitigate against the risk of a secret being exposed through source control and build processes, where it might make its way into plain text. FlexVolume (including with the above sample configuration) mitigates this risk by ensuring that secret values are never stored in files that go through source control and build processes - rather, they remain in the Vault and are only made accessible to the Pod that needs them after it has authenticated with AzureAD.

**Comment by yusmadi** [comment]
I rather use [azurerm_key_vault_secret](https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html) to retrieve secret from Azure vault and create secret in AKS using [kubernetes_secret](https://www.terraform.io/docs/providers/kubernetes/r/secret.html) which will be available as [environment variable](https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data).

**Comment by timja** [comment]
We use these libraries for reading the secrets from the file system (spring boot and node.js):
https://github.com/hmcts/properties-volume-spring-boot-starter
https://github.com/hmcts/properties-volume-nodejs

**Comment by rventuri76** [comment]
for dot net core i'm using Key-per-file Configuration Provider 
https://docs.microsoft.com/it-it/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#key-per-file-configuration-provider

**Comment by kuritka** [comment]
Hi, 

i'm curious by those two lines in  Deployment:

```
....
  subscriptionid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  tenantid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
```

At the end of the day I must  push yaml into github and not sure i I want to share this information. I don't mean it bad but using it this way adds me another layer of complexity to hide azure secrets.

**Comment by timja** [comment]
> Hi,
> 
> i'm curious by those two lines in Deployment:
> 
> ```
> ....
>   subscriptionid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
>   tenantid: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
> ```
> 
> At the end of the day I must push yaml into github and not sure i I want to share this information. I don't mean it bad but using it this way adds me another layer of complexity to hide azure secrets.

Subscription ID is no longer needed, we ended up just making tenant id public, as it was a lot more work to hide it than not.

**Comment by DeanPH** [comment]
@ritazh Is there any further movement on supporting env variables or better yet injection into Kubernetes secrets? This is currently holding us back from using this solution. We have 15 existing applications, some microservices, some SOA, that currently read from environment variables and we can't change how every application works, dev time/effort vs reward does not justify this.

First prize would be injection into Kubernetes secrets which would could use our application manifests to point to them with:
```
    envFrom:
    - secretRef:
        name: test-secret
```
or even:

```
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: backend-user
          key: backend-username
```

Thanks!
