### ISSUE TITLE
The docu lacks some details which may result in errors

### ISSUE THREAD

**Issue by malachma** [Azure/kubernetes-keyvault-flexvol#38]
The docu should  be extended, as it lakes some important Details which may result in erros like the following : 

  Warning  FailedMount            8s (x5 over 17s)  kubelet, aks-agentpool-37252822-0  MountVolume.SetUp failed for volume "test" : mount command failed, status: Failure, reason: /etc/kubernetes/volumeplugins/azure~kv/azurekeyvault-flexvolume failed, failed to get key vault

Or

Warning  FailedMount  6s (x5 over 16s)  kubelet, aks-agentpool-16481727-0  MountVolume.SetUp failed for volume "test" : mount command failed, status: Failure, reason: /etc/kubernetes/volumeplugins/azure~kv/azurekeyvault-flexvolume failed, failed to get secret passwd
 
 
1: Verify the SP values are correct

Connec to one of your agent-nodes and cat the file “cat /etc/kubernetes/azure.json”
Look for the properties "aadClientId" and "aadClientSecret", they contain the values for the clientid and the clientsecret.
With those details you are able to create the secret “kvcreds” correct:    kubectl create secret generic kvcreds --from-literal clientid=<CLIENTID> --from-literal clientsecret=<CLIENTSECRET> --type=azure/kv
 
 
2: Set the POD properties correct
 
In the sample this POD manifest is used
-->
apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds # mounting point to the pod
      options:
        usepodidentity: "false"
        keyvaultname: "testkeyvault"
        keyvaultobjectname: "testsecret"
        keyvaultobjecttype: secret # OPTIONS: secret, key, cert
        keyvaultobjectversion: "testversion"
        resourcegroup: "testresourcegroup"
        subscriptionid: "testsub"
        tenantid: "testtenant"
<--
 
Please get sure you use the correct value for keyvaultobjectversion. In the sample a string is used, but this one has actually to be a hex value like “9aff2d69ae274d69bbd23b2465bc700c”
In order to list the version for a secret you can run a command like “az keyvault secret list-versions -n passwd --vault-name malachma2”
It will print out a line with the property id and value https://malachma.vault.azure.net/secrets/passwd/9aff2d69ae274d69bbd23b2465bc700c
The last path detail is the version of the secret.
 
In order to get the subscription-id and the tenant-id this command has to be used: az accound show
You will receive an output like the following one 
{
  "environmentName": "AzureCloud",
  "id": "c98141ca-e173-46dd-9395-59a0c4xxxxxx",
  "isDefault": true,
  "name": "Microsoft Azure Internal Consumption",
  "state": "Enabled",
  "tenantId": "72f988bf-86f1-41af-91ab-2d7cd0xxxxxx",
  "user": {
    "name": "malachma@microsoft.com",
    "type": "user"
  }
}
 
3: Extend the ServicePrincipal with additional access Rights (Even if the keyvault is part of the same resource-group as the cluster is)

   a: az role assignment create --role Reader --assignee <principalid> --scope /subscriptions/<subscriptionid>/resourcegroups/<resourcegroup>/providers/Microsoft.KeyVault/vaults/<keyvaultname>
   b: az keyvault set-policy -n $KV_NAME --secret-permissions get list --spn <YOUR SPN CLIENT ID>

**Comment by robwafle** [comment]
Hi All.  I'm having trouble using this out of the box.  I've verified that my service account works by accessing the keyvault via powershell using that secret.  I've used Disconnect-AzureRmAccount to ensure I wasn't using my own credentials.   

The events I can see when I type `kubectl describe pods` is:
Events:
  Type     Reason       Age   From                      Message
  ----     ------       ----  ----                      -------
  Normal   Scheduled    2m    default-scheduler         Successfully assigned default/nginx-flex-kv to 2873k8s00000000
  Warning  FailedMount  15s   kubelet, 2873k8s00000000  Unable to mount volumes for pod "nginx-flex-kv_default(75cebd50-183c-11e9-9142-000d3a3f1db8)": timeout expired waiting for volumes to attach or mount for pod "default"/"nginx-flex-kv". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-pm764]

Can anyone help?

**Comment by ritazh** [comment]
Sorry for the delay. Few things to confirm:
 
1. I assume you are using the service principal option, not pod identity. Did you create the kvcreds k8s secret from the Azure service principal that has access to your key bault in the same namespace?
2. Can you pls share logs at /var/log/kv-driver.log from the agent node running your pod?
3. Pls share your deployment yaml file

**Comment by monteledwards** [comment]
Hi @ritazh ,  I am also having the same issue as @robwafle. 
"""
# hello-kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        volumeMounts:
          - name: test
            mountPath: /kvmnt
            readOnly: true
        ports:
        - containerPort: 8080
      volumes:
        - name: test
          flexVolume:
            driver: "azure/kv"
            secretRef:
              name: kvcreds # mounting point to the pod
            options:
              usepodidentity: "false"
              keyvaultname: "myVaultName"
              keyvaultobjectnames: "test"
              keyvaultobjecttypes: secret # OPTIONS: secret, key, cert
              resourcegroup: "myRG"
              subscriptionid: "xxxx-41b4-4231-xxxx-b9cdc4d0a95f"
              tenantid: "6660b467-add3-4d9e-8xxxda-xxxxxxx"
"""

To your questions: 
1. Yes, this is service principle authentication. I created the 'kvcreds' in the same namespace as my deployment (default). Does this need to be the same service principle that AKS uses? I have created a separate service principle for this action and as @robwafle , verified that I can get the secret externally.

2. /var/log/kv-driver.log is a non-existant file. I searched the entire filesystem and could not find this file. Is this solution only supported for AKS clusters in Azure? We use minikube locally and it would be a requirement for us to use this solution for us to be able to connect to keyvault locally.

**Comment by ritazh** [comment]
Hi @monteledwards Thank you for providing more information. 
> Does this need to be the same service principle that AKS uses

No, this service principal just needs Reader Role to the keyvault instance and have `get` access policy to the secrets you are trying to access, which should have been set if you are able to get to the secret using the az cli.

> var/log/kv-driver.log is a non-existant file

Did you look for this file on the agent node your pod is running? For example, you can look for it like this and the agent node to check is ` k8s-agentpool-40434729-1 `
```sh
kubectl get po -o wide
NAME                                READY     STATUS              RESTARTS   AGE       IP        NODE                       NOMINATED NODE
hello-kubernetes-577b854d87-6sgvr   0/1       ContainerCreating   0          5s        <none>    k8s-agentpool-40434729-1   <none>
```
From @robwafle's comments, it looks like your node is `2873k8s00000000`, are you running windows agents? This solution only supports linux.

> Is this solution only supported for AKS clusters in Azure?

No, it should work for any Kubernetes cluster provisioned on Azure. As for minikube, I have not tried it. But it _should_ work for the service principal option. But it definitely won't work with pod identity as that requires assigning Azure identities to the node resource on Azure.

**Comment by ferantivero** [comment]
@ritazh I don't want to add noise this issue/discussion. But I'm facing the non-existant issue mentioned in here with the very same description (timeout) but using pod identity.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/158487/52287160-6d523900-2948-11e9-850c-e04a743a8e6e.png">

```bash
NAME                                  READY     STATUS              RESTARTS   AGE       IP            NODE                       NOMINATED NODE
...
pod/........-75d5587458-p94q5         0/1       ContainerCreating   0          11m       <none>        aks-nodepool1-29026174-1   <none>
```

just in case, please let me share my config:

```
volumeMounts:
        - name: myname
          mountPath: /kvmnt
          readOnly: true
...
volumes:
      - name: myname
        flexVolume:
          driver: "azure/kv"
          options:
            usepodidentity: "true"
            keyvaultname: mykvname
            keyvaultobjectnames: test1;Test2
            keyvaultobjecttypes: secret;secret
            keyvaultobjectversions: ""
            resourcegroup: myrg
            subscriptionid: mysubscriptionid
            tenantid: mytenantid
```

Error:

```bash
Events:
  Type     Reason       Age               From                               Message
  ----     ------       ----              ----                               -------
  Normal   Scheduled    19m               default-scheduler                  Successfully assigned backend/....-75d5587458-p94q5 to aks-nodepool1-29026174-1
  Warning  FailedMount  1m (x8 over 17m)  kubelet, aks-nodepool1-29026174-1  Unable to mount volumes for pod "........-75d5587458-p94q5_backend(...)": timeout expired waiting for volumes to attach or mount for pod "backend"/"........-75d5587458-p94q5". list of unmounted volumes=[myname]. list of unattached volumes=[myname default-token-4j2kt]
```

**Comment by ferantivero** [comment]
@ritazh just been able to troubleshoot this. I totally missed to install flex volume in my cluster, don't ask why 😄 

After getting [flex volume option 2 installed](https://github.com/Azure/kubernetes-keyvault-flexvol#install-the-keyvault-flexvolume) it just worked like a charm and of course the ```kv-driver.log``` is in there.

**Comment by jpodoba** [comment]
> @ritazh just been able to troubleshoot this. I totally missed to install flex volume in my cluster, don't ask why 
> 
> After getting [flex volume option 2 installed](https://github.com/Azure/kubernetes-keyvault-flexvol#install-the-keyvault-flexvolume) it just worked like a charm and of course the `kv-driver.log` is in there.

Could you share where is that part for install flex volume in to cluster? I have same issue using non-rbac and pod identity. I'm suspecting that flex volume installation was missed but I cannot find where is that part :-(

**Comment by ferantivero** [comment]
@jpodoba back then I think the following instruction did the trick: https://github.com/Azure/kubernetes-keyvault-flexvol#option-2-existing-aks-cluster

**Comment by jpodoba** [comment]
Ok so I did everything from being and looks like ad pod identity working. I did a test from the pod like below:

`curl  http://169.254.169.254/metadata/identity/oauth2/token/?resource=https://vault.azure.net`

And I get Bearer token so I go further with flex volume but still have the same results.

![2019-08-14_15h26_291](https://user-images.githubusercontent.com/51724203/63024733-19e91680-bea8-11e9-89cb-eaf336b7ad8c.png)

My pod definition is:

```
apiVersion: v1
kind: Pod
metadata:
  name: access-kv
  labels:
    aadpodidbinding:  demo_app
spec:
  containers:
  - name: main-container
    image: vplauzon/get-started:part2-no-redis
    volumeMounts:
    - name: secrets
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: secrets
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"
        keyvaultname: kvXXXX # Azure Resource name for the Azure Key Vault
        keyvaultobjectnames: acr-admin-password;db-primary-master-key
        keyvaultobjecttypes: secret;secret # OPTIONS: secret, key, cert
        #keyvaultobjectversions: #  If not provided, take latest
        resourcegroup: aks-demo-resources-rg # Resource Group where the Key Vault is
        subscriptionid: 938a2cd3-xxxx-xxxx-xxxx-ff05d11f4b6f # ID of the subscription where the Key Vault is
        tenantid: 3268dbf4-xxxx-xxxx-xxxx-3a6222f2600c # AAD Tenant ID of the subscription
```

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: adpodid
spec:
  type: 0
  ResourceID: /subscriptions/938a2cd3-xxxx-xxxx-xxxx-ff05d11f4b6f/resourcegroups/aksdemo-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/adpodid
  ClientID: cde1b58b-XXXX-XXXX-XXXX-2f33971cf2f8
```

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: adpodid-binding
spec:
  AzureIdentity: adpodid
  Selector: demo_app
```
